# Generated by Django 6.0.4 on 2026-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('AGENT', 'AGENT')], default='AGENT', max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('assigned_category', models.CharField(blank=True, choices=[('SINISTRE AUTO', 'SINISTRE AUTO'), ('SERVICE CLIENT', 'SERVICE CLIENT'), ('SINISTRE VIE', 'SINISTRE VIE'), ('SINISTRE IRDS', 'SINISTRE IRDS')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
    ]
