# Generated by Django 6.0.4 on 2026-05-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
