# Generated by Django 5.2.13 on 2026-04-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_reclamation', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('urgency', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('category_assigned_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('category_assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(unique=True)),
                ('text_original', models.TextField(blank=True, null=True)),
                ('clean_text', models.TextField(blank=True, null=True)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReclamationCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('assigned_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('comment', models.OneToOneField(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='reclamations.comment')),
            ],
            options={
                'db_table': 'reclamation_cases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReclamationActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reclamations.reclamationcase')),
            ],
            options={
                'db_table': 'reclamation_action_logs',
            },
        ),
    ]
