# Generated by Django 6.0.4 on 2026-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_reclamation', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('urgency', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('review_reason', models.TextField(blank=True, null=True)),
                ('category_assigned_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('category_assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(unique=True)),
                ('text_original', models.TextField(blank=True, null=True)),
                ('clean_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReclamationCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('assigned_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reclamation_cases',
                'managed': False,
            },
        ),
    ]
