# Generated by Django 6.0.4 on 2026-04-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reclamations.reclamationcase')),
            ],
            options={
                'db_table': 'reclamation_action_logs',
            },
        ),
    ]
