# Generated by Django 6.0.4 on 2026-05-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_alter_reclamationactionlog_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
