# Generated by Django 6.0.4 on 2026-04-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamationactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamationcase',
            options={'managed': True},
        ),
    ]
