# Generated by Django 6.0.4 on 2026-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_reclamationcase_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationcase',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='reclamationcase',
            name='comment_url',
        ),
        migrations.AddField(
            model_name='reclamationcase',
            name='comment',
            field=models.OneToOneField(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='reclamations.comment'),
        ),
        migrations.AlterField(
            model_name='reclamationcase',
            name='status',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
    ]
